### ISSUE TITLE
Autocomplete not updating value 

### ISSUE THREAD

**Issue by g-demarco** [json-editor/json-editor#1124]
### General information

- json-editor version: 2.5.4

### Expected behavior

Using the autocomplete, if a value is already selected and you click on the input, the results are showed again. If you click on another result (probably the previous value is a prefix of the new results), the value should be updated.

### Actual behavior

When selecting another result without typing anything in the input, the value is selected in the autocomplete, but is not updated in the jsonschema; probably the onChange is not fired.

### Steps to reproduce the behavior

```javascript
"options": {
      "autocomplete": {
      search": "reference_system_identifier_autocomplete",
      getResultValue": "reference_system_identifier_getResultValue",
      renderResult": "reference_system_identifier_render",
      autoSelect": true
    }
},
```
I've checked the changelogs after the 2.5.4 and it doesn't seem that this issue has been addressed.

**Comment by germanbisurgi** [comment]
Could you provide the complete editor schema?

**Comment by germanbisurgi** [comment]
We were working on a test for this case. It seems to us that it working like it should.Could you please post the steps you used to reproduce this error. Better yet if you provide the autocomplete callbacks too.

**Comment by germanbisurgi** [comment]
Thanks for the context. We still need the steps you did to reproduce the problem.

**Comment by g-demarco** [comment]
Hello,
below the steps to reproduce the issue:

1) Select a result which is both a result and a prefix for other results (e.g search and select "WGS84")
![image](https://user-images.githubusercontent.com/95088761/157197613-91daa1aa-b133-4dc8-8706-d07edf7f7b52.png)

2) Click on the input so that the results are showed again, and without pressing any key, select a new result
![image](https://user-images.githubusercontent.com/95088761/157197733-5556849d-636a-4e71-921e-15b8097d28c6.png)

The value gets updated into the autocomplete component, but not in the jsonschema, as proved by the link under the input.
My intuition is that the onChange (or some other event) isn't fired in this case

**Comment by schmunk42** [comment]
I created an example here: https://is.gd/cPbrqj

Note: You need to set `window.JSONEditor.defaults.callbacks` before initializing the JSONeditor instance.

I can reproduce your issues especially when clicking a result with the mouse.
When using the keyboard (arrows) and *Enter* to select an entry it works much better. Can you confirm that?

Nonetheless it has to be fixed, it looks like an event is not fired properly when clicking an item in the list.

**Comment by germanbisurgi** [comment]
fixed in https://github.com/json-editor/json-editor/pull/1136

**Comment by joshsarosh** [comment]
Hi @schmunk42,
I'm still facing this issue. I'm using version 2.11.0.
Can you please guide me if there are any specific steps to overcome this?

**Comment by germanbisurgi** [comment]
You could take a look to the test made for the Pull request [here](https://github.com/json-editor/json-editor/blob/c5c7a33acdaf7af0168a6427917a64f0e1fa2265/tests/pages/autocomplete.html)
