### ISSUE TITLE
Checkboxes in properties dropdown does not render correctly in Bootstrap 5 theme

### ISSUE THREAD

**Issue by bkilinc** [json-editor/json-editor#1317]
### General information
Checkboxes in properties dropdown does not render correctly in Bootstrap 5 theme.

- json-editor version:

2.9.1

### Expected behavior
Checkboxes should be rendered similar to Bootstrap 4 theme.

### Actual behavior
Checkboxes are nearly invisible.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

- change theme to Bootstrap 5 
- click on properties button near section header

**Comment by schmunk42** [comment]
for reference 

![Bildschirmfoto vom 2023-04-14 14-28-21](https://user-images.githubusercontent.com/649031/232043486-4c327a19-8540-4857-b561-d214a0ba14cf.png)

**Comment by bkilinc** [comment]
if you remove `style="width: auto;"` attribute from checkboxes, they render correctly.
```
<input type="checkbox" style="width: auto;" class="form-check-input" id="1110223302521" disabled="">
```

**Comment by germanbisurgi** [comment]
Fixed in https://github.com/json-editor/json-editor/pull/1324

**Comment by bkilinc** [comment]
Problem still exists.
https://json-editor.github.io/json-editor/

**Comment by bkilinc** [comment]
> Will be fixed in the next release

Can there be a quick release for this issue in npmjs. Just asking. It really affects usability. In fact, it looks like "properties" function is broken.
