### ISSUE TITLE
minItems causing script error

### ISSUE THREAD

**Issue by Tysiana** [json-editor/json-editor#909]
### General information
I'm using @latest flag to load the jsoneditor.min.js (2.5.2)

### Expected behavior
This should make editor.validate() return an error if no option selected.

### Actual behavior
If I add 'minItems' flag to my checkboxes - it instantly causes error: jsoneditor.min.js:18 Uncaught TypeError: Cannot read property 'add' of undefined

Steps to reproduce the behavior
https://jsfiddle.net/5ce1oqy4/2/

I can't really see anything else wrong with the schema though:

```javascript
"Food": { "type": "array", "title": "Choose food", "uniqueItems": true, "format": "checkbox", "minItems": 1, "items": { "type": "string", "enum": ["bread", "noodles", "pancake"] } }
```

**Comment by robocoder** [comment]
The validation error isn't on "Food". It's on the Confirm checkbox. Booleans have two values; your enum only provides 1. Try changing it to:
```
			"Confirm": {
				"type": "boolean",
				"required": true,
				"title": "Do you accept the terms of use",
				"format": "checkbox",
				"default": false,
				"enum": [true, false]
			},
```

**Comment by Tysiana** [comment]
I think you misread my question. The form errors are ok - I'm trying to
make it so that all of them are required and at least one item from Food
category is required. I'm adding "minItems" for that but this causes script
error in the console (not form error).

**Comment by germanbisurgi** [comment]
fixed in #943

**Comment by joeskeen** [comment]
@germanbisurgi This bug still exists if you are using the `tailwind` theme.

Steps to reproduce: https://jsfiddle.net/cwh1pgj2/

If you comment out the 'theme' line, it works fine.

**Comment by germanbisurgi** [comment]
Fixed tailwind and barebones in #1201
